server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway
 
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: zhwei-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
#http://myzuul.com:9527/microservicecloud-dept/dept/get/2 之前的这种访问方式太长了，现在做个映射
zuul:
  prefix: /zhwei #设置一个统一公共前缀 http://myzuul.com:9527/zhwei/mydept/dept/get/1
#  ignored-services: microservicecloud-dept #忽略原来的方式，这个连接访问不了
  ignored-services: "*" #多个的情况下，用*来表示
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
#after request:http://myzuul.com:9527/mydept/dept/get/1

  